#pragma config(Motor,  port2,           rightwheel,    tmotorServoContinuousRotation, openLoop, driveLeft)
#pragma config(Motor,  port3,           armmotor,      tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port4,           armservo,      tmotorServoStandard, openLoop)
#pragma config(Motor,  port9,           leftwheel,     tmotorServoContinuousRotation, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//Nonexistant arm code
task arm() {
	while(true)     {
	    int btn5 = vexRT[Btn5U];

	    if (btn5) {



	    }



	wait1Msec(20);
	}




}





//This
//    Area
//        Is
//          The
//             Code
//                 For
//                    The
//                       Wheels
//this is a change
task main()
{
	//float precision = 1.311345;

startTask(arm);

int joyRight = 0;
int joyLeft = 0;

	// rightwheel values are reversed
	while (true)	{
		joyRight = vexRT[Ch2];
		joyLeft = vexRT[Ch4];
		int speed1 = vexRT[Ch2];
		int speed2 = vexRT[Ch4];

		if (vexRT[Ch2]>20)   {
			//forewards
			motor(leftwheel)=speed1;
			motor(rightwheel)=-speed1;
		}else	if (vexRT[Ch2]<-20)		{
			//backwards
			motor(leftwheel)=-speed1;
			motor(rightwheel)=speed1;
		}

		if (abs(joyRight)<20)   {
			// N U L L
			motor(leftwheel)=0;
			motor(rightwheel)=0;
		}else if (abs(joyLeft)<20)   {
			// N U L L
			motor(leftwheel)=0;
			motor(rightwheel)=0;
		}


		 if (vexRT[Ch4]<-20)   {
			//turn right
			motor(leftwheel)=speed2;
			motor(rightwheel)=speed2;
		}else if (vexRT[Ch4]>20)		{
			//turn left
			motor(leftwheel)=-speed2;
			motor(rightwheel)=-speed2;
		}












		wait1Msec(2000);
	}























}
