#pragma config(Motor,  port2,           leftwheel,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           servo1,        tmotorServoStandard, openLoop)
#pragma config(Motor,  port9,           rightwheel,    tmotorServoContinuousRotation, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//This
//    Area
//        Is
//          The
//             Code
//                 For
//                    The
//                       Wheels
task main()
{
	while (true)	{
		while (vexRT[joy1_x2]>20)   {
			motor(leftwheel)=127;
			motor(rightwheel)=127;
		}

		while (vexRT[joy1_x2]<-20)		{
			motor(leftwheel)=-127;
			motor(rightwheel)=-127;
		}


		while (vexRT[joy1_x2]<20 && vexRT[joy1_x2]>-20)   {
			motor(leftwheel)=0;
			motor(rightwheel)=0;
		}


		while (vexRT[joy1_y1]<-20)   {
			motor(leftwheel)=-127;
			motor(rightwheel)=-127;
		}

		while (vexRT[joy1_y1]>20)		{
			motor(leftwheel)=127;
			motor(rightwheel)=-127;

		}
	}

    while (true)        {

        while(vexRT[Btn6U])    {
            motor (rightwheel)=127;
				}

    }






















}