#pragma config(Sensor, in1,    potentiometer,  sensorPotentiometer)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex269_MC29, openLoop, reversed, driveRight)
#pragma config(Motor,  port4,           clawMotor,     tmotorServoStandard, openLoop)
#pragma config(Motor,  port5,           tailMotor,     tmotorVex269_MC29, openLoop, reversed, driveLeft)
#pragma config(Motor,  port6,           armMotor,      tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port9,           leftMotor,     tmotorVex269_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/* Include our other sources */
#include "controller.c"
#include "arm.c"
#include "drive.c"

/* This is the main task. */
task main()
{
	//Start Tasks
	startTask(Arm);
	startTask(ArmMove);

	/* This task must loop, or the program exits and the robot stops functioning. */
	while (true) {
		Drive();
		wait1Msec(20);
	}

	/* In case the main loop ever is coded for conditional exit, clean up tasks */
	stopTask(ArmMove);
	stopTask(Arm);
}
